### ISSUE TITLE
Fails to install on python 3.5

### ISSUE THREAD

**Issue by shadycuz** [aalok-sathe/coloring-graphs#15]
```
Traceback (most recent call last):
  File "color.py", line 1, in <module>
    import libcolgraph
  File "/home/shadycuz/.local/lib/python3.5/site-packages/libcolgraph/__init__.py", line 4, in <module>
    from libcolgraph.libpy import viz
  File "/home/shadycuz/.local/lib/python3.5/site-packages/libcolgraph/libpy/viz.py", line 9, in <module>
    import matplotlib
ImportError: No module named 'matplotlib'
```

OS="16.04.6 LTS (Xenial Xerus)"
Python="3.5.2"

Could be because of my older version, installed with ` python3 -m pip install libcolgraph --user`, installing the missing module manually fixed the problem.

**Comment by aalok-sathe** [comment]
TODO:add matplotlib to requirements.txt

**Comment by aalok-sathe** [comment]
An update should have fixed this!
