### ISSUE TITLE
Flask object has no attribute cg

### ISSUE THREAD

**Issue by shadycuz** [aalok-sathe/coloring-graphs#16]
```
colgraphweb -k 9 -i 3x3.in
 * Serving Flask app "libcolgraph.colgraphweb.__main__" (lazy loading)
 * Environment: development
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
handling GET on index!
127.0.0.1 - - [24/Dec/2019 01:27:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Dec/2019 01:27:05] "GET /static/favicon.ico HTTP/1.1" 200 -
handling POST on get_cg_data!
127.0.0.1 - - [24/Dec/2019 01:27:10] "POST /cgdata HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/shadycuz/.local/lib/python3.5/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shadycuz/.local/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shadycuz/.local/lib/python3.5/site-packages/libcolgraph/colgraphweb/__main__.py", line 233, in get_cg_data
    update_cg_data(app.cg)
AttributeError: 'Flask' object has no attribute 'cg'
```

I also tried a demo matrix from this repo and it failed with the same error. I'm guessing its something to do with the python version, matplotlib or tkinter version. 

Could you please confirm which versions you know work? 

Thanks

**Comment by aalok-sathe** [comment]
Hi,
I'm not sure what's going on here. Of course, happy to provide my versions:
-- Python 3.5.2
-- matplotlib 3.0.3

I notice you're trying to generate with 9 colors. That is a high amount of colors and will lead to a huge coloring graph for even a small base graph. We haven't tested extensively beyond 6 colors, even though in theory it should work out of the box as long as your processor can handle it.

**Comment by aalok-sathe** [comment]
For me, it works for a single vertex graph fine with 10 colors too, like so:
![](https://i.imgur.com/bQA7yG1.png)

Of course this is no comparison to your input graph, but I believe the problem you're facing is coming from elsewhere. Did you install it from source or via pip?
